apiVersion: v1
kind: Service
metadata:
  name: datanode-svc
spec:
  selector:
    app: hadoop
    tier: datanode
  ports:
    - name: datanode
      port: 9864
      targetPort: 9864
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spark-client
spec:
  selector:
    app: spark-client
  clusterIP: None
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datanode
spec:
  selector:
    matchLabels:
      app: hadoop
      tier: datanode
  template:
    metadata:
      labels:
        app: hadoop
        tier: datanode
    spec:
      containers:
        - name: spark-worker
          image: bde2020/spark-worker:3.0.1-hadoop3.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
        - image: "bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8"
          name: datanode
          envFrom:
            - configMapRef:
                name: hadoop-env
          env:
          - name: MULTIHOMED_NETWORK
            value: "0"
          - name: NAMENODE_IP
            value: "$(NAMENODE_SVC_PORT_9000_TCP_ADDR)"
          - name: NAMENODE_PORT
            value: "$(NAMENODE_SVC_PORT_9870_TCP_PORT)"
          - name: SERVICE_PRECONDITION
            value: "$(NAMENODE_IP):$(NAMENODE_PORT)"      
          - name: CORE_CONF_fs_defaultFS
            value: "hdfs://$(NAMENODE_IP):9000"       
          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: vol 
          ports:
            - containerPort: 9864
        - image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
          name: nodemanager
          envFrom:
            - configMapRef:
                name: hadoop-env
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name 
          - name: NAMENODE_IP
            value: "$(NAMENODE_SVC_PORT_9000_TCP_ADDR)"
          - name: NAMENODE_PORT
            value: "$(NAMENODE_SVC_PORT_9870_TCP_PORT)"
          - name: SERVICE_PRECONDITION
            value: "$(NAMENODE_IP):9000 $(NAMENODE_IP):9870 $(POD_NAME):9864 $(NAMENODE_IP):8088"      
          - name: YARN_CONF_yarn_resourcemanager_hostname
            value: "$(NAMENODE_IP)"
          - name: YARN_CONF_yarn_resourcemanager_address
            value: "$(NAMENODE_IP):8032"
          - name: YARN_CONF_yarn_resourcemanager_scheduler_address
            value: "$(NAMENODE_IP):8030"
          - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
            value: "$(NAMENODE_IP):8031"
          - name: CORE_CONF_fs_defaultFS
            value: "hdfs://$(NAMENODE_IP):9000" 
      volumes:
        - name: vol
