apiVersion: v1
kind: Service
metadata:
  name: namenode-svc
spec:
  selector:
    app: hadoop
    tier: namenode
  ports:
    - name: web-ui
      port: 9870
      targetPort: 9870
    - name: namenode-ipc
      port: 9000
      targetPort: 9000
    - name: yarn-web-ui
      port: 8088
      targetPort: 8088
    - name: yarn-scheduler
      port: 8030
      targetPort: 8030
    - name: yarn-jobtracker
      port: 8031
      targetPort: 8031
    - name: yarn
      port: 8032
      targetPort: 8032
    - name: datanode-dst
      port: 9866
      targetPort: 9866
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    port: 8080
    targetPort: 8080
  - name: master
    port: 7077
    targetPort: 7077
  - name: master-rest
    port: 6066
    targetPort: 6066
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
spec:
  selector:
    matchLabels:
      app: hadoop
      tier: namenode
  template:
    metadata:
      labels:
        app: hadoop
        tier: namenode
    spec:
      volumes:
        - name: vol
        - name: historyserver
        - name: hibench-src
          emptyDir: {}

      initContainers:
      - name: spark-master-init
        image: bde2020/spark-master:3.0.1-hadoop3.2
        volumeMounts:
        - name: hibench-src
          mountPath: /hibench-src
        command: ["cp", "-r", "/spark", "/hibench-src"]

      - image: "bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8"
        name: namenode-init
        volumeMounts:
        - name: hibench-src
          mountPath: /hibench-src
        command: ["cp", "-r", "/opt/hadoop-3.2.1/", "/hibench-src"]
      
      containers:
      - name: spark-master
        image: bde2020/spark-master:3.0.1-hadoop3.2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
          - containerPort: 7077
          - containerPort: 6066
        volumeMounts:
        - name: hibench-src
          mountPath: /hibench-src

      - image: "bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8"
        name: namenode
        envFrom:
          - configMapRef:
              name: hadoop-env
        env:
        - name: MULTIHOMED_NETWORK
          value: "0"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        - name: CLUSTER_NAME
          value: namenode
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://$(POD_NAME):9000"
        ports:
          - containerPort: 9870
          - containerPort: 9000
          - containerPort: 9866
        volumeMounts:
        - name: vol
          mountPath: /hadoop/dfs/name
        - name: hibench-src
          mountPath: /hibench-src
      
      - name: hibench
        image: vpemfh7/hadoop-hibench
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        - name: SPARK_MASTER
          value: spark://$(POD_NAME):7077
        - name: SPARK_HOME
          value: /sources/spark
        - name: HADOOP_HOME
          value: /sources/hadoop-3.2.1
        volumeMounts:
          - name: hibench-src
            mountPath: /sources
        command: ["/bin/bash", "-c", "--"]
        args: ["source /entrypoint.sh && while true; do sleep 30; done"]

      - image: "bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8"
        name: resourcemanager
        envFrom:
          - configMapRef:
              name: hadoop-env
        ports:
          - containerPort: 8088
          - containerPort: 8031
          - containerPort: 8030
          - containerPort: 8032
      - image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
        name: historyserver
        volumeMounts:
        - mountPath: /hadoop/yarn/timeline
          name: historyserver
        envFrom:
          - configMapRef:
              name: hadoop-env
