apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  volumes:
  - name: hibench-src 
    emptyDir: {}

  initContainers:
  - name: namenode
    image: vpemfh7/hadoop-namenode
    env:
      - name: CLUSTER_NAME
        value: teste
    volumeMounts:
    - name: hibench-src
      mountPath: /hibench-src
    command: ["cp", "-r", "/opt/hadoop-3.2.1/", "/hibench-src"]

  - name: spark-master
    image: bde2020/spark-master:3.0.1-hadoop3.2
    volumeMounts:
      - name: hibench-src
        mountPath: /hibench-src
    command: ["cp", "-r", "/spark", "/hibench-src"]

  containers:
  - name: hibench
    image: vpemfh7/hadoop-hibench
    volumeMounts:
    - name: hibench-src
      mountPath: /sources
